# Generated by Django 5.2.6 on 2025-09-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('violation_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('plate_number', models.CharField(max_length=20)),
            ],
        ),
    ]
