# Generated by Django 5.2.6 on 2025-09-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationreport',
            name='image',
            field=models.ImageField(default='', upload_to='reports/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
